const mongoose = require("mongoose");
const bcrypt = require("bcryptjs");
const env = require("./config/env");
const {
	User,
	Space,
	Booking,
	TimetableOverride,
	Organization,
	Review,
	Payment,
	Notification,
	Complaint,
	Promotion,
} = require("./models");

const DEMO_PASSWORD = "Venbok@123";
const SALT_ROUNDS = 10;

const seedDatabase = async () => {
	console.log("=================================================");
	console.log("   VenBok Pro - Enterprise Seed & Demo Engine    ");
	console.log("=================================================");

	try {
		console.log(`Connecting to MongoDB at: ${env.mongoUri}...`);
		await mongoose.connect(env.mongoUri, {
			serverSelectionTimeoutMS: 30000,
		});
		console.log("Connected to MongoDB successfully.\n");

		console.log("Clearing existing collections...");
		await Promise.all([
			User.deleteMany({}),
			Space.deleteMany({}),
			Booking.deleteMany({}),
			TimetableOverride.deleteMany({}),
			Organization.deleteMany({}),
			Review.deleteMany({}),
			Payment.deleteMany({}),
			Notification.deleteMany({}),
			Complaint.deleteMany({}),
			Promotion.deleteMany({}),
		]);
		console.log("Existing collections cleared.\n");

		// 1. Create Organization
		console.log("Seeding Organizations...");
		const org = await Organization.create({
			name: "Sri Eshwar College of Engineering",
			code: "SECE",
			type: "College",
			city: "Coimbatore",
			address: "Vadasithur Road, Kinathukadavu, Coimbatore, Tamil Nadu 641202",
			domain: "sece.ac.in",
			isVerified: true,
			settings: {
				currency: "INR",
				timezone: "Asia/Kolkata",
				allowPublicBookings: true,
			},
		});

		const corporateOrg = await Organization.create({
			name: "Coimbatore Tech Hub Venues",
			code: "CTH",
			type: "VenueChain",
			city: "Coimbatore",
			address: "Avinashi Road, Peelamedu, Coimbatore",
			domain: "techhub.com",
			isVerified: true,
		});

		// 2. Hash demo password
		const hashedPassword = await bcrypt.hash(DEMO_PASSWORD, SALT_ROUNDS);

		// 3. Create Demo Users
		console.log("Seeding Demo Users (Admin, Owner, Faculty, Student, Customer)...");
		const usersData = [
			{
				name: "Dr. S. Senthil Kumar",
				email: "admin@sece.ac.in",
				password: hashedPassword,
				phone: "+919842100001",
				role: "admin",
				roleDescription: "Dean of Student Affairs & Venue Administrator",
				status: "active",
				organizationId: org._id,
			},
			{
				name: "Platform Admin",
				email: "admin@demo.venbok.local",
				password: hashedPassword,
				phone: "+919842100002",
				role: "admin",
				roleDescription: "Platform Super Administrator",
				status: "active",
				organizationId: org._id,
			},
			{
				name: "Rajesh Varma (Venue Owner)",
				email: "owner@demo.venbok.local",
				password: hashedPassword,
				phone: "+919842100003",
				role: "owner",
				roleDescription: "Grand Convention & Banquet Hall Owner",
				status: "active",
				organizationId: corporateOrg._id,
			},
			{
				name: "Kavitha Sharma (Event Planner)",
				email: "customer@demo.venbok.local",
				password: hashedPassword,
				phone: "+919842100004",
				role: "customer",
				roleDescription: "Corporate Event Organizer & Wedding Planner",
				status: "active",
			},
			{
				name: "Prof. Arunkumar R",
				email: "faculty@sece.ac.in",
				password: hashedPassword,
				phone: "+919842100005",
				role: "faculty",
				roleDescription: "Head of Dept - Computer Science & Engineering",
				status: "active",
				organizationId: org._id,
			},
			{
				name: "faculty@demo.venbok.local",
				email: "faculty@demo.venbok.local",
				password: hashedPassword,
				phone: "+919842100006",
				role: "faculty",
				roleDescription: "Faculty Coordinator - AI & Data Science",
				status: "active",
				organizationId: org._id,
			},
			{
				name: "Dr. Priya Dharshini",
				email: "priya.it@sece.ac.in",
				password: hashedPassword,
				phone: "+919842100007",
				role: "faculty",
				roleDescription: "Associate Professor - Information Technology",
				status: "active",
				organizationId: org._id,
			},
			{
				name: "Dr. K. Rajesh",
				email: "rajesh.ece@sece.ac.in",
				password: hashedPassword,
				phone: "+919842100008",
				role: "faculty",
				roleDescription: "Professor - Electronics & Communication",
				status: "active",
				organizationId: org._id,
			},
			{
				name: "Sakthikanth R",
				email: "student@sece.ac.in",
				password: hashedPassword,
				phone: "+919842100009",
				role: "student",
				roleDescription: "CSE Final Year - Coding Club President",
				status: "active",
				organizationId: org._id,
			},
			{
				name: "student@demo.venbok.local",
				email: "student@demo.venbok.local",
				password: hashedPassword,
				phone: "+919842100010",
				role: "student",
				roleDescription: "AI & DS 3rd Year - Student Representative",
				status: "active",
				organizationId: org._id,
			},
			{
				name: "Divya M",
				email: "coordinator@sece.ac.in",
				password: hashedPassword,
				phone: "+919842100011",
				role: "coordinator",
				roleDescription: "IT 3rd Year - Hackathon Student Coordinator",
				status: "active",
				organizationId: org._id,
			},
			{
				name: "Vigneshwaran K",
				email: "vignesh.mech@sece.ac.in",
				password: hashedPassword,
				phone: "+919842100012",
				role: "student",
				roleDescription: "Mechanical Final Year - SAE Club Lead",
				status: "active",
				organizationId: org._id,
			},
		];

		const createdUsers = await User.insertMany(usersData);
		console.log(`Created ${createdUsers.length} users successfully.\n`);

		const adminUser = createdUsers.find((u) => u.email === "admin@sece.ac.in");
		const ownerUser = createdUsers.find((u) => u.email === "owner@demo.venbok.local");
		const facultyUser = createdUsers.find((u) => u.email === "faculty@sece.ac.in");
		const studentUser = createdUsers.find((u) => u.email === "student@sece.ac.in");
		const customerUser = createdUsers.find((u) => u.email === "customer@demo.venbok.local");

		// 4. Create Venues with Authentic SECE Facilities & Demo Venues
		console.log("Seeding Authentic Sri Eshwar College of Engineering (SECE) Facilities & Prototype Venues...");
		const spacesData = [
			// ── Verified Official SECE Venues ──
			{
				name: "IT Centre Auditorium",
				type: "Auditorium",
				capacity: 200,
				hourlyRate: 3500,
				dailyRate: 24000,
				city: "Coimbatore",
				address: "IT Centre, Sri Eshwar College of Engineering, Kinathukadavu",
				location: { lat: 10.8281, lng: 77.0197 },
				facilities: ["Audio Visual", "Presentation Infrastructure", "Projector", "WiFi", "Sound System"],
				verificationLevel: "Verified",
				rating: 4.9,
				reviewCount: 42,
				organizationId: org._id,
				ownerId: adminUser._id,
				imageUrl: "/venues/sece-it-centre-auditorium.jpg",
				imageSource: "Sri Eshwar College of Engineering",
				sourceUrl: "https://sece.ac.in/wp-content/uploads/2024/07/intladmissions-brochure.pdf",
				sourceName: "Sri Eshwar College of Engineering",
				imageSourceType: "official",
				isVerified: true,
				isDemo: false,
				description: "200-seat auditorium located in the IT Centre with audio-visual and presentation infrastructure.",
			},
			{
				name: "Vista Hall",
				type: "Event Hall",
				capacity: null,
				hourlyRate: 2800,
				dailyRate: 20000,
				city: "Coimbatore",
				address: "Sri Eshwar College of Engineering, Kinathukadavu",
				location: { lat: 10.8283, lng: 77.0195 },
				facilities: ["Audio Visual", "Sound System", "Presentation Infrastructure"],
				verificationLevel: "Verified",
				rating: 4.8,
				reviewCount: 35,
				organizationId: org._id,
				ownerId: adminUser._id,
				imageUrl: null,
				imageSource: null,
				sourceUrl: "https://sece.ac.in/",
				sourceName: "Sri Eshwar College of Engineering",
				imageSourceType: "official",
				isVerified: true,
				isDemo: false,
				description: "Event facility used for Industry Connect programmes, Leadership Talks, Expert Guest Lectures, Seminars and events.",
			},
			{
				name: "Synapse Studio",
				type: "IT Auditorium",
				capacity: null,
				hourlyRate: 2500,
				dailyRate: 18000,
				city: "Coimbatore",
				address: "IT Centre, Sri Eshwar College of Engineering, Kinathukadavu",
				location: { lat: 10.8282, lng: 77.0196 },
				facilities: ["Audio Visual", "Workstations", "Presentation Infrastructure"],
				verificationLevel: "Verified",
				rating: 4.8,
				reviewCount: 28,
				organizationId: org._id,
				ownerId: adminUser._id,
				imageUrl: "/venues/sece-synapse-studio.jpg",
				imageSource: "Sri Eshwar College of Engineering",
				sourceUrl: "https://sece.ac.in/wp-content/uploads/2024/07/intladmissions-brochure.pdf",
				sourceName: "Sri Eshwar College of Engineering",
				imageSourceType: "official",
				isVerified: true,
				isDemo: false,
				description: "IT auditorium used for hands-on learning sessions with industry experts and corporate professionals.",
			},
			{
				name: "Ignite Startup Accelerator - Conference Room",
				type: "Conference Room",
				capacity: null,
				hourlyRate: 2200,
				dailyRate: 15000,
				city: "Coimbatore",
				address: "Ignite Startup Accelerator, Sri Eshwar College of Engineering, Kinathukadavu",
				location: { lat: 10.8284, lng: 77.0198 },
				facilities: ["Conference Room", "Collaborative Workspace", "Discussion Space"],
				verificationLevel: "Verified",
				rating: 4.8,
				reviewCount: 31,
				organizationId: org._id,
				ownerId: adminUser._id,
				imageUrl: "/venues/sece-ignite.jpg",
				imageSource: "Sri Eshwar College of Engineering",
				sourceUrl: "https://sece.ac.in/wp-content/uploads/2024/07/intladmissions-brochure.pdf",
				sourceName: "Sri Eshwar College of Engineering",
				imageSourceType: "official",
				isVerified: true,
				isDemo: false,
				description: "Conference and collaborative discussion facility within the Ignite Startup Accelerator.",
			},
			{
				name: "Open-Air Theatre",
				type: "Open-Air Theatre",
				capacity: null,
				hourlyRate: 2000,
				dailyRate: 14000,
				city: "Coimbatore",
				address: "Sri Eshwar College of Engineering Campus, Kinathukadavu",
				location: { lat: 10.8280, lng: 77.0194 },
				facilities: ["Outdoor Stage", "Landscaped Seating", "Acoustic Green Zone"],
				verificationLevel: "Verified",
				rating: 4.9,
				reviewCount: 45,
				organizationId: org._id,
				ownerId: adminUser._id,
				imageUrl: "/venues/sece-open-air-theatre.jpg",
				imageSource: "Sri Eshwar College of Engineering",
				sourceUrl: "https://sece.ac.in/wp-content/uploads/2024/07/intladmissions-brochure.pdf",
				sourceName: "Sri Eshwar College of Engineering",
				imageSourceType: "official",
				isVerified: true,
				isDemo: false,
				description: "Outdoor amphitheatre used for cultural programmes, interactive sessions, and major college celebrations.",
			},
			{
				name: "Central Library - Reading Hall",
				type: "Reading Hall",
				capacity: 92,
				hourlyRate: 1500,
				dailyRate: 10000,
				city: "Coimbatore",
				address: "Central Library, Sri Eshwar College of Engineering, Kinathukadavu",
				location: { lat: 10.8285, lng: 77.0195 },
				facilities: ["Dedicated WiFi", "Ergonomic Seating", "Reference Section", "Digital Library"],
				verificationLevel: "Verified",
				rating: 4.8,
				reviewCount: 38,
				organizationId: org._id,
				ownerId: adminUser._id,
				imageUrl: "/venues/sece-library.jpg",
				imageSource: "Sri Eshwar College of Engineering",
				sourceUrl: "https://sece.ac.in/library-infrastructure/",
				sourceName: "Sri Eshwar College of Engineering",
				imageSourceType: "official",
				isVerified: true,
				isDemo: false,
				description: "92-seat dedicated reading hall equipped with high-speed Wi-Fi, ergonomic seating, and reference collections.",
			},

			// ── Demo Prototype Venues ──
			{
				name: "Main Auditorium",
				type: "Auditorium",
				capacity: 800,
				hourlyRate: 5000,
				dailyRate: 35000,
				city: "Coimbatore",
				address: "Dr. APJ Abdul Kalam Block, Sri Eshwar Campus, Kinathukadavu",
				location: { lat: 10.8281, lng: 77.0197 },
				facilities: ["Air Conditioning", "Stage", "Sound System", "Projector", "WiFi", "Power Backup", "Parking", "Green Rooms"],
				verificationLevel: "Unverified",
				rating: 4.9,
				reviewCount: 38,
				organizationId: org._id,
				ownerId: ownerUser._id,
				imageUrl: null,
				imageSource: null,
				sourceUrl: null,
				imageSourceType: "demo",
				isVerified: false,
				isDemo: true,
				description: "Magnificent air-conditioned convention auditorium equipped with high-fidelity line-array acoustics, motorized screen, and green rooms.",
			},
			{
				name: "Seminar Hall A",
				type: "Seminar Hall",
				capacity: 250,
				hourlyRate: 2000,
				dailyRate: 14000,
				city: "Coimbatore",
				address: "Ramanujan Academic Block, 1st Floor",
				location: { lat: 10.8285, lng: 77.0194 },
				facilities: ["Air Conditioning", "Projector", "Sound System", "WiFi", "Podium", "Power Backup"],
				verificationLevel: "Verified",
				rating: 4.7,
				reviewCount: 22,
				organizationId: org._id,
				imageUrl: null,
				imageSource: null,
				sourceUrl: null,
				imageSourceType: "demo",
				isVerified: false,
				isDemo: true,
				description: "Tiered executive seminar hall with ergonomic seating, dual laser projectors, and integrated speaker console.",
			},
			{
				name: "Seminar Hall B",
				type: "Seminar Hall",
				capacity: 180,
				hourlyRate: 1800,
				dailyRate: 12000,
				city: "Coimbatore",
				address: "Ramanujan Academic Block, 2nd Floor",
				location: { lat: 10.8287, lng: 77.0192 },
				facilities: ["Air Conditioning", "Projector", "Sound System", "WiFi", "Whiteboard"],
				verificationLevel: "Verified",
				rating: 4.6,
				reviewCount: 16,
				organizationId: org._id,
				imageUrl: null,
				imageSource: null,
				sourceUrl: null,
				imageSourceType: "demo",
				isVerified: false,
				isDemo: true,
				description: "Comfortable multimedia seminar space suitable for guest lectures, department workshops, and student society meetings.",
			},
			{
				name: "Kalam Innovation Auditorium",
				type: "Auditorium",
				capacity: 500,
				hourlyRate: 4000,
				dailyRate: 28000,
				city: "Coimbatore",
				address: "Technology Park Wing, Ground Floor",
				location: { lat: 10.829, lng: 77.02 },
				facilities: ["Air Conditioning", "Stage", "Sound System", "Projector", "Power Backup", "WiFi", "Live Streaming"],
				verificationLevel: "Premium Verified",
				rating: 4.8,
				reviewCount: 29,
				organizationId: org._id,
				ownerId: ownerUser._id,
				imageUrl: null,
				imageSource: null,
				sourceUrl: null,
				imageSourceType: "demo",
				isVerified: false,
				isDemo: true,
				description: "Flagship innovation arena with 4K projection, broadcasting suite, and breakout bays for hackathons and symposiums.",
			},
			{
				name: "Conference Room 1 (Executive)",
				type: "Meeting Room",
				capacity: 40,
				hourlyRate: 1500,
				dailyRate: 10000,
				city: "Coimbatore",
				address: "Central Administrative Block, 1st Floor",
				location: { lat: 10.8278, lng: 77.019 },
				facilities: ["Air Conditioning", "Smart Display", "Video Conferencing", "WiFi", "Coffee Station"],
				verificationLevel: "Verified",
				rating: 4.8,
				reviewCount: 19,
				organizationId: org._id,
				imageUrl: null,
				imageSource: null,
				sourceUrl: null,
				imageSourceType: "demo",
				isVerified: false,
				isDemo: true,
				description: "Premium boardroom with conference table, Cisco Webex hybrid conferencing, and surround sound.",
			},
			{
				name: "Conference Room 2 (Academic)",
				type: "Meeting Room",
				capacity: 25,
				hourlyRate: 1000,
				dailyRate: 7000,
				city: "Coimbatore",
				address: "Administrative Block, 2nd Floor",
				location: { lat: 10.8279, lng: 77.0189 },
				facilities: ["Air Conditioning", "Smart Display", "WiFi", "Whiteboard"],
				verificationLevel: "Verified",
				rating: 4.5,
				reviewCount: 12,
				organizationId: org._id,
				imageUrl: null,
				imageSource: null,
				sourceUrl: null,
				imageSourceType: "demo",
				isVerified: false,
				isDemo: true,
				description: "Compact academic discussion room tailored for department reviews, doctoral vivas, and faculty meetings.",
			},
			{
				name: "Turing Computing Laboratory",
				type: "Laboratory",
				capacity: 70,
				hourlyRate: 2500,
				dailyRate: 16000,
				city: "Coimbatore",
				address: "Computer Science Block, 1st Floor",
				location: { lat: 10.8283, lng: 77.0205 },
				facilities: ["Computer Systems", "High-Speed LAN", "Air Conditioning", "Projector", "Power Backup"],
				verificationLevel: "Verified",
				rating: 4.7,
				reviewCount: 24,
				organizationId: org._id,
				imageUrl: null,
				imageSource: null,
				sourceUrl: null,
				imageSourceType: "demo",
				isVerified: false,
				isDemo: true,
				description: "High-spec Intel Core i7 computing lab with dual gigabit switches, dedicated UPS, and automated IDE stacks.",
			},
			{
				name: "Ada Lovelace IT Lab",
				type: "Laboratory",
				capacity: 60,
				hourlyRate: 2200,
				dailyRate: 15000,
				city: "Coimbatore",
				address: "Information Technology Block, Ground Floor",
				location: { lat: 10.8281, lng: 77.0202 },
				facilities: ["Computer Systems", "Air Conditioning", "Projector", "Power Backup", "WiFi"],
				verificationLevel: "Verified",
				rating: 4.6,
				reviewCount: 18,
				organizationId: org._id,
				imageUrl: null,
				imageSource: null,
				sourceUrl: null,
				imageSourceType: "demo",
				isVerified: false,
				isDemo: true,
				description: "Modern cloud development lab configured for full-stack engineering, DevOps testing, and competitive coding.",
			},
			{
				name: "Artificial Intelligence & Deep Learning Lab",
				type: "Laboratory",
				capacity: 55,
				hourlyRate: 3000,
				dailyRate: 20000,
				city: "Coimbatore",
				address: "Tech Block, 3rd Floor",
				location: { lat: 10.8284, lng: 77.0208 },
				facilities: ["NVIDIA GPU Workstations", "Air Conditioning", "Dual Monitors", "Power Backup", "WiFi"],
				verificationLevel: "Premium Verified",
				rating: 4.9,
				reviewCount: 31,
				organizationId: org._id,
				imageUrl: null,
				imageSource: null,
				sourceUrl: null,
				imageSourceType: "demo",
				isVerified: false,
				isDemo: true,
				description: "Enterprise AI research suite featuring NVIDIA RTX GPUs, PyTorch/TensorFlow environments, and JupyterHub server access.",
			},
			{
				name: "IoT & Embedded Systems Lab",
				type: "Laboratory",
				capacity: 45,
				hourlyRate: 2000,
				dailyRate: 13000,
				city: "Coimbatore",
				address: "Electronics Block, 2nd Floor",
				location: { lat: 10.8275, lng: 77.0195 },
				facilities: ["Sensor Development Benches", "Air Conditioning", "Oscilloscopes", "Projector", "WiFi"],
				verificationLevel: "Verified",
				rating: 4.7,
				reviewCount: 15,
				organizationId: org._id,
				imageUrl: null,
				imageSource: null,
				sourceUrl: null,
				imageSourceType: "demo",
				isVerified: false,
				isDemo: true,
				description: "Equipped with Raspberry Pi 5, ESP32 modules, logic analyzers, and wireless gateway mesh testers.",
			},
			{
				name: "Robotics & Automation Arena",
				type: "Laboratory",
				capacity: 50,
				hourlyRate: 2500,
				dailyRate: 16000,
				city: "Coimbatore",
				address: "Mechanical Engineering Quad, Ground Floor",
				location: { lat: 10.8272, lng: 77.0193 },
				facilities: ["Test Arena", "Tooling Stations", "Power Backup", "Safety Barricades", "WiFi"],
				verificationLevel: "Verified",
				rating: 4.8,
				reviewCount: 20,
				organizationId: org._id,
				imageUrl: null,
				imageSource: null,
				sourceUrl: null,
				imageSourceType: "demo",
				isVerified: false,
				isDemo: true,
				description: "Spacious automation facility with robot combat arena, 3D printers, CNC laser cutter, and safety enclosure.",
			},
			{
				name: "Central Seminar Room",
				type: "Seminar Hall",
				capacity: 120,
				hourlyRate: 1500,
				dailyRate: 10000,
				city: "Coimbatore",
				address: "Library & Information Centre, 2nd Floor",
				location: { lat: 10.8286, lng: 77.0199 },
				facilities: ["Air Conditioning", "Projector", "Sound System", "WiFi", "Whiteboard"],
				verificationLevel: "Verified",
				rating: 4.6,
				reviewCount: 14,
				organizationId: org._id,
				imageUrl: null,
				imageSource: null,
				sourceUrl: null,
				imageSourceType: "demo",
				isVerified: false,
				isDemo: true,
				description: "Quiet, acoustic-treated hall inside library wing with high-speed WiFi and interactive smartboard.",
			},
			{
				name: "Open Air Amphitheatre",
				type: "Outdoor",
				capacity: 650,
				hourlyRate: 3500,
				dailyRate: 24000,
				city: "Coimbatore",
				address: "Campus Central Courtyard",
				location: { lat: 10.8282, lng: 77.0188 },
				facilities: ["Stage", "Surround Sound Cabling", "Outdoor Floodlights", "Open Sky Seating", "Parking"],
				verificationLevel: "Verified",
				rating: 4.8,
				reviewCount: 35,
				organizationId: org._id,
				ownerId: ownerUser._id,
				imageUrl: null,
				imageSource: null,
				sourceUrl: null,
				imageSourceType: "demo",
				isVerified: false,
				isDemo: true,
				description: "Roman-style stepped open amphitheatre surrounded by lush green lawns, perfect for cultural nights and rock shows.",
			},
			{
				name: "Indoor Sports & Activity Pavilion",
				type: "Sports",
				capacity: 350,
				hourlyRate: 2800,
				dailyRate: 18000,
				city: "Coimbatore",
				address: "Sports & Recreation Complex",
				location: { lat: 10.8268, lng: 77.0191 },
				facilities: ["Wooden Badminton Courts", "First Aid Room", "Sound System", "Locker Rooms", "Parking"],
				verificationLevel: "Verified",
				rating: 4.7,
				reviewCount: 27,
				organizationId: org._id,
				imageUrl: null,
				imageSource: null,
				sourceUrl: null,
				imageSourceType: "demo",
				isVerified: false,
				isDemo: true,
				description: "All-weather indoor multi-sport arena with international grade maple wood court, scoreboards, and gallery seating.",
			},
			{
				name: "Corporate Training & Placement Suite",
				type: "Training Room",
				capacity: 90,
				hourlyRate: 2000,
				dailyRate: 14000,
				city: "Coimbatore",
				address: "Career Development Centre, 1st Floor",
				location: { lat: 10.8288, lng: 77.0201 },
				facilities: ["Air Conditioning", "Interview Cubicles", "Projector", "WiFi", "Sound System"],
				verificationLevel: "Verified",
				rating: 4.8,
				reviewCount: 26,
				organizationId: org._id,
				imageUrl: null,
				imageSource: null,
				sourceUrl: null,
				imageSourceType: "demo",
				isVerified: false,
				isDemo: true,
				description: "Dedicated campus hiring suite featuring GD roundtable rooms, interview booths, and corporate presentation hall.",
			},
			{
				name: "Governing Board Room",
				type: "Meeting Room",
				capacity: 20,
				hourlyRate: 2000,
				dailyRate: 14000,
				city: "Coimbatore",
				address: "Central Secretariat, Top Floor",
				location: { lat: 10.8277, lng: 77.0187 },
				facilities: ["Luxury Leather Seating", "Air Conditioning", "Ultra HD Video Wall", "Secure WiFi", "Pantry"],
				verificationLevel: "Premium Verified",
				rating: 5.0,
				reviewCount: 11,
				organizationId: org._id,
				imageUrl: null,
				imageSource: null,
				sourceUrl: null,
				imageSourceType: "demo",
				isVerified: false,
				isDemo: true,
				description: "Executive trustee boardroom with state-of-the-art interactive display, document visualizers, and catering pantry.",
			},
			{
				name: "Multipurpose Workshop Hall",
				type: "Workshop",
				capacity: 200,
				hourlyRate: 2200,
				dailyRate: 15000,
				city: "Coimbatore",
				address: "Mechanical & Civil Complex, 1st Floor",
				location: { lat: 10.8271, lng: 77.0198 },
				facilities: ["Heavy 3-Phase Power", "Projector", "Exhaust Systems", "Workbenches", "Parking"],
				verificationLevel: "Verified",
				rating: 4.6,
				reviewCount: 17,
				organizationId: org._id,
				imageUrl: null,
				imageSource: null,
				sourceUrl: null,
				imageSourceType: "demo",
				isVerified: false,
				isDemo: true,
				description: "Heavy-duty hands-on workshop with modular partition layout, three-phase power drops, and overhead crane rails.",
			},
			{
				name: "Cultural & Performing Arts Hall",
				type: "Event Hall",
				capacity: 350,
				hourlyRate: 3000,
				dailyRate: 21000,
				city: "Coimbatore",
				address: "Student Activity Centre, Ground Floor",
				location: { lat: 10.8284, lng: 77.0185 },
				facilities: ["Raised Stage", "Acoustic Wall Panels", "Air Conditioning", "Green Room", "Sound System"],
				verificationLevel: "Verified",
				rating: 4.8,
				reviewCount: 30,
				organizationId: org._id,
				ownerId: ownerUser._id,
				imageUrl: null,
				imageSource: null,
				sourceUrl: null,
				imageSourceType: "demo",
				isVerified: false,
				isDemo: true,
				description: "Dynamic performing arts auditorium with proscenium stage, backstage makeup rooms, and customizable theatrical spots.",
			},
			{
				name: "Sri Eshwar Incubation & Startup Hub",
				type: "Innovation Space",
				capacity: 100,
				hourlyRate: 2500,
				dailyRate: 17000,
				city: "Coimbatore",
				address: "Research & Development Block, 2nd Floor",
				location: { lat: 10.8289, lng: 77.0204 },
				facilities: ["Coworking Desks", "Private Meeting Pods", "Gigabit Internet", "Coffee Bar", "Air Conditioning"],
				verificationLevel: "Premium Verified",
				rating: 4.9,
				reviewCount: 25,
				organizationId: org._id,
				imageUrl: null,
				imageSource: null,
				sourceUrl: null,
				imageSourceType: "demo",
				isVerified: false,
				isDemo: true,
				description: "Silicon Valley-style vibrant startup incubator featuring open collaborative hot desks, pitch deck lounge, and podcast studio.",
			},
			{
				name: "ECE Design & Simulation Center",
				type: "Laboratory",
				capacity: 60,
				hourlyRate: 2200,
				dailyRate: 15000,
				city: "Coimbatore",
				address: "Electronics Block, 3rd Floor",
				location: { lat: 10.8276, lng: 77.0197 },
				facilities: ["Cadence EDA Tools", "Dual Display PCs", "Air Conditioning", "Projector", "WiFi"],
				verificationLevel: "Verified",
				rating: 4.7,
				reviewCount: 16,
				organizationId: org._id,
				imageUrl: null,
				imageSource: null,
				sourceUrl: null,
				imageSourceType: "demo",
				isVerified: false,
				isDemo: true,
				description: "Semiconductor modeling lab loaded with Synopsys and Cadence IC design suites, FPGA testing rigs, and signal generators.",
			},
		];

		const normalizedSpacesData = spacesData.map((s) => ({
			isVerified: s.isVerified !== undefined ? s.isVerified : false,
			isDemo: s.isDemo !== undefined ? s.isDemo : true,
			sourceName: s.sourceName || (s.isVerified ? "Sri Eshwar College of Engineering" : "VenBok Prototype Demo"),
			sourceUrl: s.sourceUrl !== undefined ? s.sourceUrl : null,
			imageSource: s.imageSource || (s.imageUrl ? "Unsplash Demo Imagery" : null),
			...s,
			verificationLevel: s.isVerified ? "Verified" : "Unverified",
		}));

		const createdSpaces = await Space.insertMany(normalizedSpacesData);
		console.log(`Created ${createdSpaces.length} spaces successfully.\n`);

		const spaceMap = new Map();
		createdSpaces.forEach((s) => spaceMap.set(s.name, s._id));

		// 5. Create Timetable Overrides (Academic Schedule Blocks)
		console.log("Seeding Timetable Overrides...");
		const overridesData = [
			{
				spaceId: spaceMap.get("Turing Computing Laboratory"),
				date: "2026-09-24",
				start: "09:00",
				end: "11:00",
				status: "academic",
			},
			{
				spaceId: spaceMap.get("Ada Lovelace IT Lab"),
				date: "2026-09-24",
				start: "14:00",
				end: "16:00",
				status: "academic",
			},
			{
				spaceId: spaceMap.get("Artificial Intelligence & Deep Learning Lab"),
				date: "2026-09-25",
				start: "10:00",
				end: "12:00",
				status: "academic",
			},
			{
				spaceId: spaceMap.get("Seminar Hall A"),
				date: "2026-09-25",
				start: "09:00",
				end: "11:00",
				status: "academic",
			},
			{
				spaceId: spaceMap.get("IoT & Embedded Systems Lab"),
				date: "2026-09-26",
				start: "11:00",
				end: "13:00",
				status: "academic",
			},
			{
				spaceId: spaceMap.get("Robotics & Automation Arena"),
				date: "2026-09-28",
				start: "14:00",
				end: "16:00",
				status: "academic",
			},
			{
				spaceId: spaceMap.get("Central Seminar Room"),
				date: "2026-10-05",
				start: "10:00",
				end: "12:00",
				status: "academic",
			},
			{
				spaceId: spaceMap.get("ECE Design & Simulation Center"),
				date: "2026-10-08",
				start: "09:00",
				end: "12:00",
				status: "academic",
			},
		];

		const createdOverrides = await TimetableOverride.insertMany(overridesData);
		console.log(`Created ${createdOverrides.length} timetable overrides successfully.\n`);

		// 6. Create 42 Bookings with lifecycle and requirement checks (Free Institutional Use)
		console.log("Seeding 42 Institutional Bookings with Requirements...");
		const bookingsData = [
			// --- Verified SECE Venue Bookings ---
			{
				title: "Global Tech Industry Leadership Keynote",
				type: "Conference",
				spaceId: spaceMap.get("IT Centre Auditorium"),
				date: "2026-09-28",
				start: "10:00",
				end: "13:00",
				participants: 180,
				organizedBy: "Department of Information Technology",
				notes: "Executive presentation with corporate industry delegates and faculty mentors.",
				requestedBy: "Dr. Priya Dharshini",
				requestedRole: "faculty",
				userId: facultyUser._id,
				status: "Approved",
				requirements: { catering: false, soundSystem: true, stageSetup: true, liveStreaming: false, powerBackup: true },
			},
			{
				title: "Industry Connect: AI & Autonomous Systems Seminar",
				type: "Seminar",
				spaceId: spaceMap.get("Vista Hall"),
				date: "2026-09-29",
				start: "14:00",
				end: "17:00",
				participants: 90,
				organizedBy: "Sri Eshwar Industry Relations Cell",
				notes: "Guest lecture on state-of-the-art autonomous systems and robotics engineering.",
				requestedBy: "Prof. Arunkumar R",
				requestedRole: "faculty",
				userId: facultyUser._id,
				status: "Approved",
				requirements: { catering: false, soundSystem: true, stageSetup: false, liveStreaming: false, powerBackup: true },
			},

			// --- Past Bookings (September 2026) ---
			{
				title: "National Level AI & Cloud Symposium 2026",
				type: "Seminar",
				spaceId: spaceMap.get("Main Auditorium"),
				date: "2026-09-10",
				start: "09:00",
				end: "16:00",
				participants: 650,
				organizedBy: "CSE & AI-DS Department",
				notes: "Inaugurated by Industry Chief Guest from Microsoft. Keynotes and project demos.",
				requestedBy: "Prof. Arunkumar R",
				requestedRole: "faculty",
				userId: facultyUser._id,
				status: "Completed",
				requirements: { catering: true, soundSystem: true, stageSetup: true, liveStreaming: true, powerBackup: true },
			},
			{
				title: "Hands-on Flutter & Web3 DevSprint",
				type: "Workshop",
				spaceId: spaceMap.get("Ada Lovelace IT Lab"),
				date: "2026-09-12",
				start: "09:00",
				end: "13:00",
				participants: 55,
				organizedBy: "Google Developer Student Club",
				notes: "Practical coding session with live deployment on Vercel.",
				requestedBy: "Sakthikanth R",
				requestedRole: "student",
				userId: studentUser._id,
				status: "Completed",
				requirements: { powerBackup: true },
			},
			{
				title: "TCS / Infosys Placement Aptitude BootCamp",
				type: "Training",
				spaceId: spaceMap.get("Corporate Training & Placement Suite"),
				date: "2026-09-14",
				start: "09:00",
				end: "17:00",
				participants: 85,
				organizedBy: "Career Development Centre",
				notes: "Phase 1 aptitude and logical reasoning crash course for pre-final years.",
				requestedBy: "Dr. S. Senthil Kumar",
				requestedRole: "admin",
				userId: adminUser._id,
				status: "Completed",
				requirements: { powerBackup: true },
			},
			{
				title: "IoT Smart Agriculture Prototype Showcase",
				type: "Workshop",
				spaceId: spaceMap.get("IoT & Embedded Systems Lab"),
				date: "2026-09-15",
				start: "14:00",
				end: "17:00",
				participants: 40,
				organizedBy: "ECE Department",
				notes: "Hardware kit demonstration with sensor calibration.",
				requestedBy: "Dr. K. Rajesh",
				requestedRole: "faculty",
				status: "Completed",
			},
			{
				title: "SECE Rotaract Youth Leadership Assembly",
				type: "Club",
				spaceId: spaceMap.get("Seminar Hall B"),
				date: "2026-09-16",
				start: "14:00",
				end: "17:00",
				participants: 120,
				organizedBy: "Rotaract Club of SECE",
				notes: "Induction of new student office bearers and annual plan announcement.",
				requestedBy: "Divya M",
				requestedRole: "coordinator",
				status: "Completed",
			},
			{
				title: "Cyber Security & Ethical Hacking Crash Course",
				type: "Training",
				spaceId: spaceMap.get("Turing Computing Laboratory"),
				date: "2026-09-18",
				start: "10:00",
				end: "16:00",
				participants: 60,
				organizedBy: "IT Department",
				notes: "Vulnerability analysis and CTF lab session.",
				requestedBy: "Dr. Priya Dharshini",
				requestedRole: "faculty",
				status: "Completed",
			},
			{
				title: "SAE E-Baja Electric Vehicle Design Review",
				type: "Club",
				spaceId: spaceMap.get("Multipurpose Workshop Hall"),
				date: "2026-09-19",
				start: "10:00",
				end: "13:00",
				participants: 80,
				organizedBy: "Mechanical SAE Collegiate Club",
				notes: "Chassis structural audit and battery thermal testing report presentation.",
				requestedBy: "Vigneshwaran K",
				requestedRole: "student",
				status: "Completed",
			},
			{
				title: "Annual Faculty Research & Publications Conclave",
				type: "Seminar",
				spaceId: spaceMap.get("Seminar Hall A"),
				date: "2026-09-20",
				start: "09:00",
				end: "13:00",
				participants: 200,
				organizedBy: "Research & Development Cell",
				notes: "Review of Scopus/SCI journal submissions and seed funding grants.",
				requestedBy: "Prof. Arunkumar R",
				requestedRole: "faculty",
				status: "Completed",
			},
			{
				title: "Robotics Club Internal Line-Follower Trials",
				type: "Club",
				spaceId: spaceMap.get("Robotics & Automation Arena"),
				date: "2026-09-21",
				start: "14:00",
				end: "18:00",
				participants: 45,
				organizedBy: "SECE Robotics Club",
				notes: "Track testing for state level bot race competition.",
				requestedBy: "Sakthikanth R",
				requestedRole: "student",
				status: "Completed",
			},
			{
				title: "Executive Dean Council Quarterly Meeting",
				type: "Seminar",
				spaceId: spaceMap.get("Governing Board Room"),
				date: "2026-09-22",
				start: "10:00",
				end: "13:00",
				participants: 18,
				organizedBy: "Principal Secretariat",
				notes: "Autonomous curriculum syllabus ratification and academic audit.",
				requestedBy: "Dr. S. Senthil Kumar",
				requestedRole: "admin",
				status: "Completed",
			},
			{
				title: "Late Night Gaming & Esports Tournament",
				type: "Club",
				spaceId: spaceMap.get("Central Seminar Room"),
				date: "2026-09-22",
				start: "14:00",
				end: "18:00",
				participants: 110,
				organizedBy: "Informal Gaming Society",
				notes: "Non-academic event requested during internal assessment prep week.",
				requestedBy: "Sakthikanth R",
				requestedRole: "student",
				status: "Rejected",
				rejectionReason: "Non-academic event requested during internal assessment study week.",
			},

			// --- Current / Immediate Bookings (Today: 2026-09-24 & 2026-09-25) ---
			{
				title: "Eshwar TechFest 2026 Inaugural Ceremony",
				type: "Seminar",
				spaceId: spaceMap.get("Main Auditorium"),
				date: "2026-09-24",
				start: "09:00",
				end: "13:00",
				participants: 750,
				organizedBy: "All Engineering Departments",
				notes: "Chief Guest address, cultural lamp lighting and banner reveal.",
				requestedBy: "Dr. S. Senthil Kumar",
				requestedRole: "admin",
				status: "Confirmed",
				requirements: { soundSystem: true, stageSetup: true, liveStreaming: true, powerBackup: true },
			},
			{
				title: "Campus to Corporate: Resume & Soft Skills Training",
				type: "Training",
				spaceId: spaceMap.get("Corporate Training & Placement Suite"),
				date: "2026-09-24",
				start: "10:00",
				end: "16:00",
				participants: 80,
				organizedBy: "Placement Cell",
				notes: "Interactive corporate etiquette and group discussion simulation.",
				requestedBy: "Dr. Priya Dharshini",
				requestedRole: "faculty",
				status: "Approved",
			},
			{
				title: "Algorithmic Problem Solving & LeetCode Jam",
				type: "Club",
				spaceId: spaceMap.get("Turing Computing Laboratory"),
				date: "2026-09-24",
				start: "14:00",
				end: "17:00",
				participants: 65,
				organizedBy: "Competitive Coding Guild",
				notes: "Graph algorithms and dynamic programming speed rounds.",
				requestedBy: "Sakthikanth R",
				requestedRole: "student",
				status: "Approved",
			},
			{
				title: "Unapproved Heavy Sound Rehearsal",
				type: "Club",
				spaceId: spaceMap.get("Conference Room 1 (Executive)"),
				date: "2026-09-24",
				start: "14:00",
				end: "16:00",
				participants: 35,
				organizedBy: "Cultural Club Rehearsal",
				notes: "Conference room is not suitable for musical rehearsals.",
				requestedBy: "Divya M",
				requestedRole: "coordinator",
				status: "Rejected",
				rejectionReason: "Executive conference room cannot be booked for musical rehearsals.",
			},
			{
				title: "AI Startup Pitch & Angel Investor Showcase",
				type: "Workshop",
				spaceId: spaceMap.get("Sri Eshwar Incubation & Startup Hub"),
				date: "2026-09-25",
				start: "09:30",
				end: "13:30",
				participants: 75,
				organizedBy: "Center for Innovation and Entrepreneurship",
				notes: "Top 10 student startups pitching to seed accelerators.",
				requestedBy: "Prof. Arunkumar R",
				requestedRole: "faculty",
				status: "Approved",
			},
			{
				title: "Full-Stack React & Node System Architecture Seminar",
				type: "Seminar",
				spaceId: spaceMap.get("Central Seminar Room"),
				date: "2026-09-25",
				start: "13:00",
				end: "17:00",
				participants: 110,
				organizedBy: "CSE & IT Associations",
				notes: "Deep-dive into microservices, authentication, and state management.",
				requestedBy: "Dr. Priya Dharshini",
				requestedRole: "faculty",
				status: "Approved",
			},
			{
				title: "Inter-College Autonomous Drone Racing League",
				type: "Workshop",
				spaceId: spaceMap.get("Indoor Sports & Activity Pavilion"),
				date: "2026-09-25",
				start: "14:00",
				end: "18:00",
				participants: 250,
				organizedBy: "SECE Drone Research Lab",
				notes: "Mesh cage arena setup with FPV drone obstacle course.",
				requestedBy: "Sakthikanth R",
				requestedRole: "student",
				status: "Pending",
			},

			// --- Upcoming / Pending / Approved Bookings (Late September & October 2026) ---
			{
				title: "36-Hour National Smart India Hackathon Internal Round",
				type: "Hackathon",
				spaceId: spaceMap.get("Kalam Innovation Auditorium"),
				date: "2026-09-28",
				start: "09:00",
				end: "18:00",
				participants: 350,
				organizedBy: "Innovation & SIH Cell",
				notes: "Continuous overnight hackathon with mentor evaluations and food stall passes.",
				requestedBy: "Divya M",
				requestedRole: "coordinator",
				status: "Confirmed",
				requirements: { powerBackup: true, soundSystem: true, stageSetup: true },
			},
			{
				title: "VLSI Layout Design & Cadence Tool Training",
				type: "Training",
				spaceId: spaceMap.get("ECE Design & Simulation Center"),
				date: "2026-09-29",
				start: "09:00",
				end: "16:00",
				participants: 55,
				organizedBy: "ECE Department",
				notes: "Industry resource person from Synopsys India.",
				requestedBy: "Dr. K. Rajesh",
				requestedRole: "faculty",
				status: "Approved",
			},
			{
				title: "AWS Cloud Practitioner Certification BootCamp",
				type: "Training",
				spaceId: spaceMap.get("Seminar Hall A"),
				date: "2026-10-01",
				start: "09:00",
				end: "17:00",
				participants: 220,
				organizedBy: "AWS Cloud Academy SECE",
				notes: "Hands-on cloud architecture voucher preparation.",
				requestedBy: "Prof. Arunkumar R",
				requestedRole: "faculty",
				status: "Approved",
			},
			{
				title: "Global Alumni Meet & Mentorship Roundtable",
				type: "Seminar",
				spaceId: spaceMap.get("Main Auditorium"),
				date: "2026-10-03",
				start: "09:30",
				end: "15:30",
				participants: 600,
				organizedBy: "SECE Alumni Association",
				notes: "Distinguished alumni award presentation and campus networking lunch.",
				requestedBy: "Dr. S. Senthil Kumar",
				requestedRole: "admin",
				status: "Approved",
				requirements: { catering: true, stageSetup: true, soundSystem: true },
			},
			{
				title: "Open Source Club Linux Kernel Compilation Fest",
				type: "Club",
				spaceId: spaceMap.get("Turing Computing Laboratory"),
				date: "2026-10-05",
				start: "13:00",
				end: "17:00",
				participants: 60,
				organizedBy: "FOSS Club",
				notes: "Custom distro building and git rebase masterclass.",
				requestedBy: "Sakthikanth R",
				requestedRole: "student",
				status: "Pending",
			},
			{
				title: "Mechanical CFD & Thermal Analysis Hands-on",
				type: "Workshop",
				spaceId: spaceMap.get("Multipurpose Workshop Hall"),
				date: "2026-10-06",
				start: "09:00",
				end: "13:00",
				participants: 140,
				organizedBy: "Mechanical Engineering Dept",
				notes: "Ansys Fluent simulation for aerodynamic models.",
				requestedBy: "Vigneshwaran K",
				requestedRole: "student",
				status: "Approved",
			},
			{
				title: "Women in Engineering (IEEE WIE) Leadership Summit",
				type: "Seminar",
				spaceId: spaceMap.get("Seminar Hall B"),
				date: "2026-10-08",
				start: "10:00",
				end: "15:00",
				participants: 160,
				organizedBy: "IEEE SECE Student Branch",
				notes: "Panel discussion with tech leaders from Google and Qualcomm.",
				requestedBy: "Dr. Priya Dharshini",
				requestedRole: "faculty",
				status: "Approved",
			},
			{
				title: "SECE Annual Music & Choreography Band Rehearsal",
				type: "Club",
				spaceId: spaceMap.get("Cultural & Performing Arts Hall"),
				date: "2026-10-09",
				start: "14:00",
				end: "18:00",
				participants: 120,
				organizedBy: "Cultural Troupe",
				notes: "Audio stage setup and acoustic tuning.",
				requestedBy: "Divya M",
				requestedRole: "coordinator",
				status: "Approved",
			},
			{
				title: "Cyber Security Hackathon: DEFCON SECE Edition",
				type: "Hackathon",
				spaceId: spaceMap.get("Kalam Innovation Auditorium"),
				date: "2026-10-12",
				start: "08:00",
				end: "18:00",
				participants: 400,
				organizedBy: "Cyber Cell & Police Dept",
				notes: "Red team vs Blue team cyber range scenario.",
				requestedBy: "Prof. Arunkumar R",
				requestedRole: "faculty",
				status: "Pending",
			},
			{
				title: "ECE Industry Advisory Board Curriculum Meet",
				type: "Seminar",
				spaceId: spaceMap.get("Conference Room 1 (Executive)"),
				date: "2026-10-13",
				start: "10:00",
				end: "13:00",
				participants: 35,
				organizedBy: "ECE Department Board of Studies",
				notes: "Industry 5.0 alignment and semiconductor elective updates.",
				requestedBy: "Dr. K. Rajesh",
				requestedRole: "faculty",
				status: "Pending",
			},
			{
				title: "Deep Learning with PyTorch for Medical Imaging",
				type: "Workshop",
				spaceId: spaceMap.get("Artificial Intelligence & Deep Learning Lab"),
				date: "2026-10-15",
				start: "09:00",
				end: "16:00",
				participants: 50,
				organizedBy: "AI & Data Science Department",
				notes: "Hands-on GPU workstations required. Kaggle dataset benchmark.",
				requestedBy: "Prof. Arunkumar R",
				requestedRole: "faculty",
				status: "Approved",
			},
			{
				title: "Tamil Literary Club Pattimandram & Folk Arts",
				type: "Club",
				spaceId: spaceMap.get("Open Air Amphitheatre"),
				date: "2026-10-16",
				start: "16:00",
				end: "19:00",
				participants: 500,
				organizedBy: "Muthamizh Mandram",
				notes: "Traditional lighting, podium and surround audio speakers.",
				requestedBy: "Sakthikanth R",
				requestedRole: "student",
				status: "Pending",
			},
			{
				title: "Infosys Springboard Tech Mentorship",
				type: "Training",
				spaceId: spaceMap.get("Corporate Training & Placement Suite"),
				date: "2026-10-17",
				start: "09:00",
				end: "13:00",
				participants: 75,
				organizedBy: "Industry Institute Partnership Cell",
				notes: "Full-day mentor session on industry Java microservices.",
				requestedBy: "Dr. Priya Dharshini",
				requestedRole: "faculty",
				status: "Pending",
			},
			{
				title: "Inter-College Basketball & Volleyball Championship",
				type: "Club",
				spaceId: spaceMap.get("Indoor Sports & Activity Pavilion"),
				date: "2026-10-20",
				start: "08:00",
				end: "17:00",
				participants: 300,
				organizedBy: "Physical Education Department",
				notes: "First aid medical desk and referee stage reservation.",
				requestedBy: "Dr. S. Senthil Kumar",
				requestedRole: "admin",
				status: "Approved",
			},
			{
				title: "Robotics Drone Night Testing (Overnight)",
				type: "Club",
				spaceId: spaceMap.get("Robotics & Automation Arena"),
				date: "2026-10-21",
				start: "18:00",
				end: "22:00",
				participants: 60,
				organizedBy: "Student Drone Club",
				notes: "Late night testing without required safety and faculty in-charge.",
				requestedBy: "Sakthikanth R",
				requestedRole: "student",
				status: "Rejected",
				rejectionReason: "Overnight facility usage requires approved safety supervisor presence.",
			},
			{
				title: "National Conference on Green Energy & EV Powertrains",
				type: "Seminar",
				spaceId: spaceMap.get("Main Auditorium"),
				date: "2026-10-24",
				start: "09:00",
				end: "17:00",
				participants: 700,
				organizedBy: "EEE & Mechanical Engineering Depts",
				notes: "Co-sponsored by MNRE. Delegates from 40 engineering institutes.",
				requestedBy: "Vigneshwaran K",
				requestedRole: "student",
				status: "Pending",
			},
			{
				title: "Generative AI Agent Architecture Masterclass",
				type: "Workshop",
				spaceId: spaceMap.get("Seminar Hall A"),
				date: "2026-10-26",
				start: "09:30",
				end: "16:30",
				participants: 230,
				organizedBy: "Department of AI & Data Science",
				notes: "Multi-agent systems, LangGraph, and RAG pipelines on Gemini.",
				requestedBy: "Prof. Arunkumar R",
				requestedRole: "faculty",
				status: "Pending",
			},
			{
				title: "Google Solution Challenge Ideathon",
				type: "Hackathon",
				spaceId: spaceMap.get("Sri Eshwar Incubation & Startup Hub"),
				date: "2026-10-28",
				start: "09:00",
				end: "18:00",
				participants: 90,
				organizedBy: "GDSC SECE",
				notes: "UN Sustainable Development Goals student innovation contest.",
				requestedBy: "Divya M",
				requestedRole: "coordinator",
				status: "Pending",
			},
			{
				title: "ECE VLSI DSP Architecture Lab Exam",
				type: "Training",
				spaceId: spaceMap.get("ECE Design & Simulation Center"),
				date: "2026-11-02",
				start: "09:00",
				end: "13:00",
				participants: 58,
				organizedBy: "ECE Academic Cell",
				notes: "End semester autonomous practical examination.",
				requestedBy: "Dr. K. Rajesh",
				requestedRole: "faculty",
				status: "Approved",
			},
			{
				title: "Placement Mock Technical Interview Marathon",
				type: "Training",
				spaceId: spaceMap.get("Central Seminar Room"),
				date: "2026-11-04",
				start: "09:00",
				end: "17:00",
				participants: 100,
				organizedBy: "Career Development Centre",
				notes: "Alumni panels conducting individual 1-on-1 coding interview rounds.",
				requestedBy: "Dr. S. Senthil Kumar",
				requestedRole: "admin",
				status: "Approved",
			},
			{
				title: "SECE Annual Fine Arts & Photography Gala",
				type: "Club",
				spaceId: spaceMap.get("Cultural & Performing Arts Hall"),
				date: "2026-11-07",
				start: "10:00",
				end: "17:00",
				participants: 300,
				organizedBy: "Fine Arts Club",
				notes: "Gallery display boards and spotlight illumination.",
				requestedBy: "Divya M",
				requestedRole: "coordinator",
				status: "Pending",
			},
			{
				title: "National Conference on Advanced Materials & Robotics",
				type: "Seminar",
				spaceId: spaceMap.get("Seminar Hall B"),
				date: "2026-11-10",
				start: "09:00",
				end: "16:00",
				participants: 170,
				organizedBy: "Mechatronics Department",
				notes: "Poster presentations and live telecast to overseas speakers.",
				requestedBy: "Vigneshwaran K",
				requestedRole: "student",
				status: "Pending",
			},
			{
				title: "Amazon AWS DeepRacer Reinforcement Learning League",
				type: "Hackathon",
				spaceId: spaceMap.get("Indoor Sports & Activity Pavilion"),
				date: "2026-11-14",
				start: "09:00",
				end: "17:00",
				participants: 280,
				organizedBy: "CSE & AWS Club",
				notes: "Physical 1/18th scale autonomous vehicle track tournament.",
				requestedBy: "Sakthikanth R",
				requestedRole: "student",
				status: "Pending",
			},
			{
				title: "Governing Council Strategic Budget Review",
				type: "Seminar",
				spaceId: spaceMap.get("Governing Board Room"),
				date: "2026-11-16",
				start: "10:00",
				end: "14:00",
				participants: 18,
				organizedBy: "Board of Trustees",
				notes: "Financial budget allocations for academic year 2026-2027.",
				requestedBy: "Dr. S. Senthil Kumar",
				requestedRole: "admin",
				status: "Approved",
			},
		];

		const createdBookings = await Booking.insertMany(bookingsData);
		console.log(`Created ${createdBookings.length} bookings successfully.\n`);

		// 7. Seed Verified Reviews
		console.log("Seeding Verified Customer Reviews...");
		const reviewsData = [
			{
				spaceId: spaceMap.get("Main Auditorium"),
				userId: facultyUser._id,
				rating: 5,
				categories: { cleanliness: 5, facilities: 5, staff: 5, valueForMoney: 5 },
				comment: "World-class acoustic system and stage lighting. Hosted over 700 delegates without any technical glitch. Outstanding venue!",
				status: "Approved",
			},
			{
				spaceId: spaceMap.get("Main Auditorium"),
				userId: customerUser._id,
				rating: 5,
				categories: { cleanliness: 5, facilities: 5, staff: 4, valueForMoney: 5 },
				comment: "Spacious green rooms and pristine air conditioning. Excellent support from the stage technicians.",
				status: "Approved",
			},
			{
				spaceId: spaceMap.get("Kalam Innovation Auditorium"),
				userId: studentUser._id,
				rating: 5,
				categories: { cleanliness: 5, facilities: 5, staff: 5, valueForMoney: 5 },
				comment: "The best venue for our 36-hour hackathon. Non-stop power backup and ultra-fast WiFi throughout the night!",
				status: "Approved",
			},
			{
				spaceId: spaceMap.get("Turing Computing Laboratory"),
				userId: studentUser._id,
				rating: 4,
				categories: { cleanliness: 5, facilities: 4, staff: 4, valueForMoney: 5 },
				comment: "All Linux terminals were set up cleanly. Fast gigabit network made our coding speed tests frictionless.",
				status: "Approved",
			},
			{
				spaceId: spaceMap.get("Sri Eshwar Incubation & Startup Hub"),
				userId: facultyUser._id,
				rating: 5,
				categories: { cleanliness: 5, facilities: 5, staff: 5, valueForMoney: 4 },
				comment: "Visiting angel investors loved the open aesthetic and professional presentation lounge.",
				status: "Approved",
			},
			{
				spaceId: spaceMap.get("Open Air Amphitheatre"),
				userId: studentUser._id,
				rating: 5,
				categories: { cleanliness: 4, facilities: 5, staff: 5, valueForMoney: 5 },
				comment: "Unmatched open-sky vibe during our cultural band performance. Sound projection across the steps was crystal clear.",
				status: "Approved",
			},
		];
		await Review.insertMany(reviewsData);
		console.log(`Created ${reviewsData.length} reviews successfully.\n`);

		// 8. Seed Promotions
		console.log("Seeding Active Promotions & Offers...");
		const promotionsData = [
			{
				ownerId: ownerUser._id,
				spaceId: spaceMap.get("Main Auditorium"),
				title: "Grand Autumn Fest Discount",
				code: "TECHFEST20",
				discountPercent: 20,
				validFrom: "2026-09-01",
				validTo: "2026-10-31",
				description: "Flat 20% off for multi-day conferences and educational symposiums.",
				isActive: true,
			},
			{
				ownerId: ownerUser._id,
				spaceId: spaceMap.get("Kalam Innovation Auditorium"),
				title: "Early Bird Hackathon Special",
				code: "HACKATHON15",
				discountPercent: 15,
				validFrom: "2026-09-15",
				validTo: "2026-11-30",
				description: "15% discount for verified student hackathons and technical clubs.",
				isActive: true,
			},
			{
				ownerId: ownerUser._id,
				title: "Weekday Seminar Flash Deal",
				code: "WEEKDAY10",
				discountPercent: 10,
				validFrom: "2026-09-01",
				validTo: "2026-12-31",
				description: "Save 10% on Monday to Thursday seminar room reservations.",
				isActive: true,
			},
		];
		await Promotion.insertMany(promotionsData);
		console.log(`Created ${promotionsData.length} active promotions.\n`);

		// 9. Seed In-App Notifications
		console.log("Seeding Notifications...");
		const notificationsData = [
			{
				userId: facultyUser._id,
				title: "Booking Request Approved",
				message: "Your booking for 'National Level AI & Cloud Symposium 2026' in Main Auditorium has been approved by the Dean.",
				type: "approval",
				link: "/bookings",
				isRead: true,
			},
			{
				userId: facultyUser._id,
				title: "New Review Received",
				message: "Dr. Priya posted a 5-star review for the Incubation Hub workshop.",
				type: "system",
				link: "/spaces",
				isRead: false,
			},
			{
				userId: adminUser._id,
				title: "Pending Booking Approvals (12)",
				message: "There are 12 new venue booking requests awaiting administrative review.",
				type: "booking",
				link: "/dashboard/admin",
				isRead: false,
			},
			{
				userId: studentUser._id,
				title: "Venue Reservation Confirmed",
				message: "Reservation for Algorithmic Problem Solving Jam in Turing Lab is confirmed for internal campus use.",
				type: "booking",
				link: "/bookings",
				isRead: false,
			},
		];
		await Notification.insertMany(notificationsData);
		console.log(`Created ${notificationsData.length} in-app notifications.\n`);

		// 10. Seed Complaints / Disputes
		console.log("Seeding Complaint & Support Tickets...");
		const complaintsData = [
			{
				userId: facultyUser._id,
				spaceId: spaceMap.get("Seminar Hall A"),
				subject: "Projector HDMI Cable loose connection",
				category: "Venue Facility Issue",
				description: "The primary ceiling projector flickered during slide changeover. Technicians should replace the patch cable.",
				status: "Resolved",
				ownerResponse: "Campus AV team has installed a brand new 4K high-speed Braided HDMI line.",
				adminNotes: "Closed after verification by campus maintenance.",
			},
			{
				userId: studentUser._id,
				spaceId: spaceMap.get("Indoor Sports & Activity Pavilion"),
				subject: "Court Lighting Delay during tournament",
				category: "Venue Facility Issue",
				description: "Two floodlight panels took 15 minutes to turn on after power switchover.",
				status: "Under Review",
				ownerResponse: "Electrician reviewing capacitor ballast units.",
				adminNotes: "Scheduled for inspection on weekend.",
			},
		];
		await Complaint.insertMany(complaintsData);
		console.log(`Created ${complaintsData.length} dispute & support records.\n`);

		console.log("=================================================");
		console.log("        VENBOK PRO SEEDING COMPLETED             ");
		console.log("=================================================");
		console.log("Demo Accounts (Password: Venbok@123):");
		console.log("1. Admin: admin@sece.ac.in (or admin@demo.venbok.local)");
		console.log("2. Venue Owner: owner@demo.venbok.local");
		console.log("3. Customer / Planner: customer@demo.venbok.local");
		console.log("4. Faculty: faculty@sece.ac.in");
		console.log("5. Student: student@sece.ac.in");
		console.log("=================================================\n");

		await mongoose.disconnect();
		process.exit(0);
	} catch (error) {
		console.error("Seeding failed with error:", error);
		process.exit(1);
	}
};

seedDatabase();
